# Generated by Django 4.2.4 on 2023-08-19 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('production_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('active_ingredients', models.TextField(blank=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('usage_instructions', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_images/')),
                ('is_prescription_required', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer')),
            ],
        ),
    ]
