# Generated by Django 4.2.4 on 2023-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
